[package]
name = "hello-org"
version = "0.1.0"
edition = "2025"

# Optional metadata
authors = ["extrise <nayanchandradas@hotmail.com>"]
description = "A simple hello world project for org testing"

[dependencies]
